# For more information, please refer to https://aka.ms/vscode-docker-python
FROM quay.io/unstructured-io/unstructured:0.6.3

# Keeps Python from generating .pyc files in the container
ENV PYTHONDONTWRITEBYTECODE=1

# Turns off buffering for easier container logging
ENV PYTHONUNBUFFERED=1



